### ISSUE TITLE
Bad configuration example for jobs, target contain item, should contain list of items 

### ISSUE THREAD

**Issue by jscotka** [packit-service/packit.dev#85]
see https://packit.dev/docs/configuration/#packit-service-jobs
there is example: 
```
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets: fedora-stable
```

 but expected is ``list`` of targets `` targets: [fedora-stable]``

maybe this issue appears on more places in this doc. Maybe ``dist-git-branch: fedora-all`` is also bad?
