### ISSUE TITLE
Outdated Configuration#User configuration file

### ISSUE THREAD

**Issue by jpopelka** [packit-service/packit.dev#87]
[Minimal sample config](https://packit.dev/docs/configuration/#minimal-sample-config-1) says:

```yaml
debug: true
github_token: mnbvcxz123456
pagure_user_token: qwertyuiop098765
```

while I think it now should be
```yaml
debug: true

authentication:
  github.com:
    token: mnbvcxz123456
  pagure:
    token: qwertyuiop098765
    instance_url: https://src.fedoraproject.org
```
